// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechTrove.DAL;

#nullable disable

namespace TechTrove.DAL.Migrations
{
    [DbContext(typeof(TechTroveContext))]
    [Migration("20240518142647_AddOrderToUser")]
    partial class AddOrderToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechTrove.DAL.Entities.TechTroveOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TechTroveUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TechTroveUserId");

                    b.ToTable("TechTroveOrders");
                });

            modelBuilder.Entity("TechTrove.DAL.Entities.TechTroveUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailConfirmed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumberConfirmed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TechTroveUsers");
                });

            modelBuilder.Entity("TechTrove.DAL.Entities.TechTroveOrder", b =>
                {
                    b.HasOne("TechTrove.DAL.Entities.TechTroveUser", "TechTroveUser")
                        .WithMany("TechTroveOrders")
                        .HasForeignKey("TechTroveUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechTroveUser");
                });

            modelBuilder.Entity("TechTrove.DAL.Entities.TechTroveUser", b =>
                {
                    b.Navigation("TechTroveOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
